// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef CSR_ETH_H
#define CSR_ETH_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - csr_eth::ctrl
#define CSR_ETH__CTRL__START_bm 0x1
#define CSR_ETH__CTRL__START_bp 0
#define CSR_ETH__CTRL__START_bw 1
#define CSR_ETH__CTRL__START_reset 0x0

// reg - csr_eth::status
#define CSR_ETH__STATUS__BUSY_bm 0x1
#define CSR_ETH__STATUS__BUSY_bp 0
#define CSR_ETH__STATUS__BUSY_bw 1
#define CSR_ETH__STATUS__BUSY_reset 0x0

// reg - csr_eth::loopback_ctrl
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_DIRECT_LVL_bm 0x1
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_DIRECT_LVL_bp 0
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_DIRECT_LVL_bw 1
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_DIRECT_LVL_reset 0x0
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ANALYZER_LVL_bm 0x2
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ANALYZER_LVL_bp 1
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ANALYZER_LVL_bw 1
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ANALYZER_LVL_reset 0x0
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ETH_IP_LVL_bm 0x4
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ETH_IP_LVL_bp 2
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ETH_IP_LVL_bw 1
#define CSR_ETH__LOOPBACK_CTRL__LOOPBACK_ETH_IP_LVL_reset 0x0

// reg - csr_eth::tx_length
#define CSR_ETH__TX_LENGTH__VALUE_bm 0xffff
#define CSR_ETH__TX_LENGTH__VALUE_bp 0
#define CSR_ETH__TX_LENGTH__VALUE_bw 16
#define CSR_ETH__TX_LENGTH__VALUE_reset 0x3c

// reg - csr_eth::frame_count
#define CSR_ETH__FRAME_COUNT__VALUE_bm 0xffffffff
#define CSR_ETH__FRAME_COUNT__VALUE_bp 0
#define CSR_ETH__FRAME_COUNT__VALUE_bw 32
#define CSR_ETH__FRAME_COUNT__VALUE_reset 0x1

// reg - csr_eth::ifg_cycles
#define CSR_ETH__IFG_CYCLES__VALUE_bm 0xffffffff
#define CSR_ETH__IFG_CYCLES__VALUE_bp 0
#define CSR_ETH__IFG_CYCLES__VALUE_bw 32
#define CSR_ETH__IFG_CYCLES__VALUE_reset 0x0

// reg - csr_eth::dst_mac_l
#define CSR_ETH__DST_MAC_L__VALUE_bm 0xffffffff
#define CSR_ETH__DST_MAC_L__VALUE_bp 0
#define CSR_ETH__DST_MAC_L__VALUE_bw 32
#define CSR_ETH__DST_MAC_L__VALUE_reset 0xffffffff

// reg - csr_eth::dst_mac_h
#define CSR_ETH__DST_MAC_H__VALUE_bm 0xffffffff
#define CSR_ETH__DST_MAC_H__VALUE_bp 0
#define CSR_ETH__DST_MAC_H__VALUE_bw 32
#define CSR_ETH__DST_MAC_H__VALUE_reset 0xffff

// reg - csr_eth::src_mac_l
#define CSR_ETH__SRC_MAC_L__VALUE_bm 0xffffffff
#define CSR_ETH__SRC_MAC_L__VALUE_bp 0
#define CSR_ETH__SRC_MAC_L__VALUE_bw 32
#define CSR_ETH__SRC_MAC_L__VALUE_reset 0x2

// reg - csr_eth::src_mac_h
#define CSR_ETH__SRC_MAC_H__VALUE_bm 0xffffffff
#define CSR_ETH__SRC_MAC_H__VALUE_bp 0
#define CSR_ETH__SRC_MAC_H__VALUE_bw 32
#define CSR_ETH__SRC_MAC_H__VALUE_reset 0x1234

// reg - csr_eth::ethertype
#define CSR_ETH__ETHERTYPE__VALUE_bm 0xffff
#define CSR_ETH__ETHERTYPE__VALUE_bp 0
#define CSR_ETH__ETHERTYPE__VALUE_bw 16
#define CSR_ETH__ETHERTYPE__VALUE_reset 0x800

// reg - csr_eth::ipv4_src
#define CSR_ETH__IPV4_SRC__VALUE_bm 0xffffffff
#define CSR_ETH__IPV4_SRC__VALUE_bp 0
#define CSR_ETH__IPV4_SRC__VALUE_bw 32
#define CSR_ETH__IPV4_SRC__VALUE_reset 0xc0a80102

// reg - csr_eth::ipv4_dst
#define CSR_ETH__IPV4_DST__VALUE_bm 0xffffffff
#define CSR_ETH__IPV4_DST__VALUE_bp 0
#define CSR_ETH__IPV4_DST__VALUE_bw 32
#define CSR_ETH__IPV4_DST__VALUE_reset 0xc0a8015a

// reg - csr_eth::ipv4_cfg0
#define CSR_ETH__IPV4_CFG0__TTL_bm 0xff
#define CSR_ETH__IPV4_CFG0__TTL_bp 0
#define CSR_ETH__IPV4_CFG0__TTL_bw 8
#define CSR_ETH__IPV4_CFG0__TTL_reset 0x40
#define CSR_ETH__IPV4_CFG0__PROTOCOL_bm 0xff00
#define CSR_ETH__IPV4_CFG0__PROTOCOL_bp 8
#define CSR_ETH__IPV4_CFG0__PROTOCOL_bw 8
#define CSR_ETH__IPV4_CFG0__PROTOCOL_reset 0x11
#define CSR_ETH__IPV4_CFG0__DSCP_ECN_bm 0xff0000
#define CSR_ETH__IPV4_CFG0__DSCP_ECN_bp 16
#define CSR_ETH__IPV4_CFG0__DSCP_ECN_bw 8
#define CSR_ETH__IPV4_CFG0__DSCP_ECN_reset 0x0

// reg - csr_eth::ipv4_cfg1
#define CSR_ETH__IPV4_CFG1__IDENTIFICATION_bm 0xffff
#define CSR_ETH__IPV4_CFG1__IDENTIFICATION_bp 0
#define CSR_ETH__IPV4_CFG1__IDENTIFICATION_bw 16
#define CSR_ETH__IPV4_CFG1__IDENTIFICATION_reset 0x0
#define CSR_ETH__IPV4_CFG1__FLAGS_bm 0x70000
#define CSR_ETH__IPV4_CFG1__FLAGS_bp 16
#define CSR_ETH__IPV4_CFG1__FLAGS_bw 3
#define CSR_ETH__IPV4_CFG1__FLAGS_reset 0x2
#define CSR_ETH__IPV4_CFG1__FRAGMENT_OFFSET_bm 0xfff80000
#define CSR_ETH__IPV4_CFG1__FRAGMENT_OFFSET_bp 19
#define CSR_ETH__IPV4_CFG1__FRAGMENT_OFFSET_bw 13
#define CSR_ETH__IPV4_CFG1__FRAGMENT_OFFSET_reset 0x0

// reg - csr_eth::ipv4_checksum
#define CSR_ETH__IPV4_CHECKSUM__VALUE_bm 0xffff
#define CSR_ETH__IPV4_CHECKSUM__VALUE_bp 0
#define CSR_ETH__IPV4_CHECKSUM__VALUE_bw 16
#define CSR_ETH__IPV4_CHECKSUM__VALUE_reset 0x0

// reg - csr_eth::udp_ports
#define CSR_ETH__UDP_PORTS__SRC_PORT_bm 0xffff
#define CSR_ETH__UDP_PORTS__SRC_PORT_bp 0
#define CSR_ETH__UDP_PORTS__SRC_PORT_bw 16
#define CSR_ETH__UDP_PORTS__SRC_PORT_reset 0x4d2
#define CSR_ETH__UDP_PORTS__DST_PORT_bm 0xffff0000
#define CSR_ETH__UDP_PORTS__DST_PORT_bp 16
#define CSR_ETH__UDP_PORTS__DST_PORT_bw 16
#define CSR_ETH__UDP_PORTS__DST_PORT_reset 0x4d3

// reg - csr_eth::udp_length
#define CSR_ETH__UDP_LENGTH__VALUE_bm 0xffff
#define CSR_ETH__UDP_LENGTH__VALUE_bp 0
#define CSR_ETH__UDP_LENGTH__VALUE_bw 16
#define CSR_ETH__UDP_LENGTH__VALUE_reset 0x0

// reg - csr_eth::udp_checksum
#define CSR_ETH__UDP_CHECKSUM__VALUE_bm 0xffff
#define CSR_ETH__UDP_CHECKSUM__VALUE_bp 0
#define CSR_ETH__UDP_CHECKSUM__VALUE_bw 16
#define CSR_ETH__UDP_CHECKSUM__VALUE_reset 0x0

// reg - csr_eth::tx_data_0
#define CSR_ETH__TX_DATA_0__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_0__VALUE_bp 0
#define CSR_ETH__TX_DATA_0__VALUE_bw 32
#define CSR_ETH__TX_DATA_0__VALUE_reset 0x0

// reg - csr_eth::tx_data_1
#define CSR_ETH__TX_DATA_1__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_1__VALUE_bp 0
#define CSR_ETH__TX_DATA_1__VALUE_bw 32
#define CSR_ETH__TX_DATA_1__VALUE_reset 0x0

// reg - csr_eth::tx_data_2
#define CSR_ETH__TX_DATA_2__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_2__VALUE_bp 0
#define CSR_ETH__TX_DATA_2__VALUE_bw 32
#define CSR_ETH__TX_DATA_2__VALUE_reset 0x0

// reg - csr_eth::tx_data_3
#define CSR_ETH__TX_DATA_3__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_3__VALUE_bp 0
#define CSR_ETH__TX_DATA_3__VALUE_bw 32
#define CSR_ETH__TX_DATA_3__VALUE_reset 0x0

// reg - csr_eth::tx_data_4
#define CSR_ETH__TX_DATA_4__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_4__VALUE_bp 0
#define CSR_ETH__TX_DATA_4__VALUE_bw 32
#define CSR_ETH__TX_DATA_4__VALUE_reset 0x0

// reg - csr_eth::tx_data_5
#define CSR_ETH__TX_DATA_5__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_5__VALUE_bp 0
#define CSR_ETH__TX_DATA_5__VALUE_bw 32
#define CSR_ETH__TX_DATA_5__VALUE_reset 0x0

// reg - csr_eth::tx_data_6
#define CSR_ETH__TX_DATA_6__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_6__VALUE_bp 0
#define CSR_ETH__TX_DATA_6__VALUE_bw 32
#define CSR_ETH__TX_DATA_6__VALUE_reset 0x0

// reg - csr_eth::tx_data_7
#define CSR_ETH__TX_DATA_7__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_7__VALUE_bp 0
#define CSR_ETH__TX_DATA_7__VALUE_bw 32
#define CSR_ETH__TX_DATA_7__VALUE_reset 0x0

// reg - csr_eth::tx_data_8
#define CSR_ETH__TX_DATA_8__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_8__VALUE_bp 0
#define CSR_ETH__TX_DATA_8__VALUE_bw 32
#define CSR_ETH__TX_DATA_8__VALUE_reset 0x0

// reg - csr_eth::tx_data_9
#define CSR_ETH__TX_DATA_9__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_9__VALUE_bp 0
#define CSR_ETH__TX_DATA_9__VALUE_bw 32
#define CSR_ETH__TX_DATA_9__VALUE_reset 0x0

// reg - csr_eth::tx_data_10
#define CSR_ETH__TX_DATA_10__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_10__VALUE_bp 0
#define CSR_ETH__TX_DATA_10__VALUE_bw 32
#define CSR_ETH__TX_DATA_10__VALUE_reset 0x0

// reg - csr_eth::tx_data_11
#define CSR_ETH__TX_DATA_11__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_11__VALUE_bp 0
#define CSR_ETH__TX_DATA_11__VALUE_bw 32
#define CSR_ETH__TX_DATA_11__VALUE_reset 0x0

// reg - csr_eth::tx_data_12
#define CSR_ETH__TX_DATA_12__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_12__VALUE_bp 0
#define CSR_ETH__TX_DATA_12__VALUE_bw 32
#define CSR_ETH__TX_DATA_12__VALUE_reset 0x0

// reg - csr_eth::tx_data_13
#define CSR_ETH__TX_DATA_13__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_13__VALUE_bp 0
#define CSR_ETH__TX_DATA_13__VALUE_bw 32
#define CSR_ETH__TX_DATA_13__VALUE_reset 0x0

// reg - csr_eth::tx_data_14
#define CSR_ETH__TX_DATA_14__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_14__VALUE_bp 0
#define CSR_ETH__TX_DATA_14__VALUE_bw 32
#define CSR_ETH__TX_DATA_14__VALUE_reset 0x0

// reg - csr_eth::tx_data_15
#define CSR_ETH__TX_DATA_15__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_15__VALUE_bp 0
#define CSR_ETH__TX_DATA_15__VALUE_bw 32
#define CSR_ETH__TX_DATA_15__VALUE_reset 0x0

// reg - csr_eth::tx_data_16
#define CSR_ETH__TX_DATA_16__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_16__VALUE_bp 0
#define CSR_ETH__TX_DATA_16__VALUE_bw 32
#define CSR_ETH__TX_DATA_16__VALUE_reset 0x0

// reg - csr_eth::tx_data_17
#define CSR_ETH__TX_DATA_17__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_17__VALUE_bp 0
#define CSR_ETH__TX_DATA_17__VALUE_bw 32
#define CSR_ETH__TX_DATA_17__VALUE_reset 0x0

// reg - csr_eth::tx_data_18
#define CSR_ETH__TX_DATA_18__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_18__VALUE_bp 0
#define CSR_ETH__TX_DATA_18__VALUE_bw 32
#define CSR_ETH__TX_DATA_18__VALUE_reset 0x0

// reg - csr_eth::tx_data_19
#define CSR_ETH__TX_DATA_19__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_19__VALUE_bp 0
#define CSR_ETH__TX_DATA_19__VALUE_bw 32
#define CSR_ETH__TX_DATA_19__VALUE_reset 0x0

// reg - csr_eth::tx_data_20
#define CSR_ETH__TX_DATA_20__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_20__VALUE_bp 0
#define CSR_ETH__TX_DATA_20__VALUE_bw 32
#define CSR_ETH__TX_DATA_20__VALUE_reset 0x0

// reg - csr_eth::tx_data_21
#define CSR_ETH__TX_DATA_21__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_21__VALUE_bp 0
#define CSR_ETH__TX_DATA_21__VALUE_bw 32
#define CSR_ETH__TX_DATA_21__VALUE_reset 0x0

// reg - csr_eth::tx_data_22
#define CSR_ETH__TX_DATA_22__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_22__VALUE_bp 0
#define CSR_ETH__TX_DATA_22__VALUE_bw 32
#define CSR_ETH__TX_DATA_22__VALUE_reset 0x0

// reg - csr_eth::tx_data_23
#define CSR_ETH__TX_DATA_23__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_23__VALUE_bp 0
#define CSR_ETH__TX_DATA_23__VALUE_bw 32
#define CSR_ETH__TX_DATA_23__VALUE_reset 0x0

// reg - csr_eth::tx_data_24
#define CSR_ETH__TX_DATA_24__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_24__VALUE_bp 0
#define CSR_ETH__TX_DATA_24__VALUE_bw 32
#define CSR_ETH__TX_DATA_24__VALUE_reset 0x0

// reg - csr_eth::tx_data_25
#define CSR_ETH__TX_DATA_25__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_25__VALUE_bp 0
#define CSR_ETH__TX_DATA_25__VALUE_bw 32
#define CSR_ETH__TX_DATA_25__VALUE_reset 0x0

// reg - csr_eth::tx_data_26
#define CSR_ETH__TX_DATA_26__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_26__VALUE_bp 0
#define CSR_ETH__TX_DATA_26__VALUE_bw 32
#define CSR_ETH__TX_DATA_26__VALUE_reset 0x0

// reg - csr_eth::tx_data_27
#define CSR_ETH__TX_DATA_27__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_27__VALUE_bp 0
#define CSR_ETH__TX_DATA_27__VALUE_bw 32
#define CSR_ETH__TX_DATA_27__VALUE_reset 0x0

// reg - csr_eth::tx_data_28
#define CSR_ETH__TX_DATA_28__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_28__VALUE_bp 0
#define CSR_ETH__TX_DATA_28__VALUE_bw 32
#define CSR_ETH__TX_DATA_28__VALUE_reset 0x0

// reg - csr_eth::tx_data_29
#define CSR_ETH__TX_DATA_29__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_29__VALUE_bp 0
#define CSR_ETH__TX_DATA_29__VALUE_bw 32
#define CSR_ETH__TX_DATA_29__VALUE_reset 0x0

// reg - csr_eth::tx_data_30
#define CSR_ETH__TX_DATA_30__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_30__VALUE_bp 0
#define CSR_ETH__TX_DATA_30__VALUE_bw 32
#define CSR_ETH__TX_DATA_30__VALUE_reset 0x0

// reg - csr_eth::tx_data_31
#define CSR_ETH__TX_DATA_31__VALUE_bm 0xffffffff
#define CSR_ETH__TX_DATA_31__VALUE_bp 0
#define CSR_ETH__TX_DATA_31__VALUE_bw 32
#define CSR_ETH__TX_DATA_31__VALUE_reset 0x0

// addrmap - csr_eth
typedef struct __attribute__ ((__packed__)) {
    uint32_t ctrl;
    uint32_t status;
    uint32_t loopback_ctrl;
    uint32_t tx_length;
    uint32_t frame_count;
    uint8_t RESERVED_14_17[0x4];
    uint32_t ifg_cycles;
    uint8_t RESERVED_1c_1f[0x4];
    uint32_t dst_mac_l;
    uint32_t dst_mac_h;
    uint32_t src_mac_l;
    uint32_t src_mac_h;
    uint32_t ethertype;
    uint8_t RESERVED_34_3f[0xc];
    uint32_t ipv4_src;
    uint32_t ipv4_dst;
    uint32_t ipv4_cfg0;
    uint32_t ipv4_cfg1;
    uint32_t ipv4_checksum;
    uint8_t RESERVED_54_5f[0xc];
    uint32_t udp_ports;
    uint32_t udp_length;
    uint32_t udp_checksum;
    uint8_t RESERVED_6c_ff[0x94];
    uint32_t tx_data_0;
    uint32_t tx_data_1;
    uint32_t tx_data_2;
    uint32_t tx_data_3;
    uint32_t tx_data_4;
    uint32_t tx_data_5;
    uint32_t tx_data_6;
    uint32_t tx_data_7;
    uint32_t tx_data_8;
    uint32_t tx_data_9;
    uint32_t tx_data_10;
    uint32_t tx_data_11;
    uint32_t tx_data_12;
    uint32_t tx_data_13;
    uint32_t tx_data_14;
    uint32_t tx_data_15;
    uint32_t tx_data_16;
    uint32_t tx_data_17;
    uint32_t tx_data_18;
    uint32_t tx_data_19;
    uint32_t tx_data_20;
    uint32_t tx_data_21;
    uint32_t tx_data_22;
    uint32_t tx_data_23;
    uint32_t tx_data_24;
    uint32_t tx_data_25;
    uint32_t tx_data_26;
    uint32_t tx_data_27;
    uint32_t tx_data_28;
    uint32_t tx_data_29;
    uint32_t tx_data_30;
    uint32_t tx_data_31;
} csr_eth_t;


static_assert(sizeof(csr_eth_t) == 0x180, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* CSR_ETH_H */
